# Generated by Django 5.2.5 on 2026-03-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0003_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snacks',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
