# Generated by Django 5.2.5 on 2026-03-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0004_remove_menu_breakfast_remove_menu_dinner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('menu_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('items', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_type',
        ),
        migrations.AddField(
            model_name='menu',
            name='breakfast',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='dinner',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='snacks',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
