# Generated by Django 5.2.5 on 2026-03-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0005_addmenu_remove_menu_items_remove_menu_menu_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addmenu',
            new_name='Adminaddmenu',
        ),
    ]
