# Generated by Django 5.2.11 on 2026-03-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0006_rename_addmenu_adminaddmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
