# Generated by Django 5.2.11 on 2026-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0007_delete_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaddmenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
