# Generated by Django 5.2.11 on 2026-03-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0008_adminaddmenu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaddmenu',
            name='menu_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], max_length=20),
        ),
    ]
