# Generated by Django 5.2.5 on 2026-03-04 17:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0009_alter_adminaddmenu_menu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='Ordered', max_length=20)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enteapp.adminaddmenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enteapp.login')),
            ],
        ),
    ]
