# Generated by Django 5.2.11 on 2026-03-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0011_remove_order_status_remove_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Evening', 'Evening')], max_length=20)),
                ('preferred_item', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
