# Generated by Django 5.2.11 on 2026-03-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0014_order_login_alter_order_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
