# Generated by Django 5.2.11 on 2026-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0016_order_login_order_description_order_menu_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='LOGIN',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
