# Generated by Django 5.2.11 on 2026-03-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0017_remove_complaint_login_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enteapp.login'),
            preserve_default=False,
        ),
    ]
