# Generated by Django 5.2.11 on 2026-04-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enteapp', '0018_complaint_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='department',
        ),
    ]
